import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail
} from 'react-icons/ai'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nguyen Xuan Hoang Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>HOANG NGUYEN</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className=' bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2>Nguyen Xuan Hoang</h2>
            <h3>Full-stack developer / Platform validation engineer</h3>
            <p>
              An engineer who provides web services for programming, design content needs and
              platform validation. Join me down below and let's get started!
            </p>
          </div>
          <div>
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillMail />
          </div>
        </section>
      </main>
    </>
  )
}
